spring:
  datasource:
    url: jdbc:mysql://mysql-neurl:3306/neurl-db?allowPublicKeyRetrieval=true&useSSL=FALSE
    username: neurl
    password: neurl
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update